using MassTransit;
using Messages.Traffic.Analytics;
using NotificationData.Repositories.DeliveryLogs;
using NotificationData.Repositories.Notifications;
using NotificationStore.Business.Email;
using NotificationStore.Publishers.Logs;

namespace NotificationStore.Consumers;

public class SummaryAnalyticsConsumer : IConsumer<SummaryAnalyticsMessage>
{
    private readonly INotificationRepository _repo;
    private readonly IDeliveryLogRepository _logRepo;
    private readonly INotificationLogPublisher _logPublisher;
    private readonly IEmailService _emailService;

    private const string Domain = "[CONSUMER][ANALYTICS][SUMMARY]";

    public SummaryAnalyticsConsumer(
        INotificationRepository repo,
        IDeliveryLogRepository logRepo,
        INotificationLogPublisher logPublisher,
        IEmailService emailService)
    {
        _repo = repo;
        _logRepo = logRepo;
        _logPublisher = logPublisher;
        _emailService = emailService;
    }

    public async Task Consume(ConsumeContext<SummaryAnalyticsMessage> context)
    {
        var msg = context.Message;

        await _logPublisher.PublishAuditAsync(
            domain: Domain,
            messageText: $"{Domain} Summary received for {msg.Intersection}",
            category: "ANALYTICS",
            operation: "Consume",
            data: new Dictionary<string, object>
            {
                ["Intersection"] = msg.Intersection
            });

        var subs = await _repo.GetSubscribersAsync(msg.Intersection, "Summary");

        foreach (var sub in subs)
        {
            var subject = $"Daily Summary: {msg.Intersection}";
            var body = $@"
            <html>
            <body style='font-family:Segoe UI,Roboto,Helvetica,Arial,sans-serif;background-color:#f9fafb;padding:24px;'>
                <div style='max-width:600px;margin:auto;background:#ffffff;border-radius:8px;padding:24px;'>
                <h2 style='color:#047857;'>Daily Traffic Summary — {msg.Intersection}</h2>
                <table style='width:100%;border-collapse:collapse;margin-top:10px;'>
                    <tr><td>Vehicles</td><td><strong>{msg.VehicleCount}</strong></td></tr>
                    <tr><td>Pedestrians</td><td><strong>{msg.PedestrianCount}</strong></td></tr>
                    <tr><td>Cyclists</td><td><strong>{msg.CyclistCount}</strong></td></tr>
                    <tr><td>Incidents</td><td><strong>{msg.IncidentsDetected}</strong></td></tr>
                    <tr><td>Average Congestion</td><td><strong>{msg.AverageCongestion * 100:F1}%</strong></td></tr>
                </table>
                <p style='margin-top:24px;'>This is an automated summary generated by the UNIWA STLS Traffic Analytics Service.</p>
                <p style='font-size:13px;color:#6b7280;'>UNIWA STLS Notification Service</p>
                </div>
            </body>
            </html>";

            try
            {
                await _emailService.SendEmailAsync(sub.UserEmail, subject, body);
                await _logRepo.LogDeliveryAsync(sub.UserId, sub.UserEmail, $"{msg.Intersection}.summary", "Success");

                await _logPublisher.PublishAuditAsync(
                    domain: Domain,
                    messageText: $"{Domain} Email delivered to {sub.UserEmail}",
                    category: "EMAIL",
                    operation: "SendEmail",
                    data: new Dictionary<string, object>
                    {
                        ["UserEmail"] = sub.UserEmail,
                        ["Intersection"] = msg.Intersection
                    });
            }
            catch (Exception ex)
            {
                await _logRepo.LogDeliveryAsync(sub.UserId, sub.UserEmail, $"{msg.Intersection}.summary", "Failed");

                await _logPublisher.PublishErrorAsync(
                    domain: Domain,
                    messageText: $"{Domain} Email failed for {sub.UserEmail}: {ex.Message}",
                    operation: "SendEmail",
                    data: new Dictionary<string, object>
                    {
                        ["UserEmail"] = sub.UserEmail,
                        ["Intersection"] = msg.Intersection,
                        ["Error"] = ex.Message
                    });
            }
        }
    }
}
