// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrafficAnalyticsData;

#nullable disable

namespace TrafficAnalyticsData.Migrations
{
    [DbContext(typeof(TrafficAnalyticsDbContext))]
    [Migration("20251026225356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrafficAnalyticsData.Entities.AlertEntity", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlertId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Intersection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IntersectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AlertId");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("TrafficAnalyticsData.Entities.DailySummaryEntity", b =>
                {
                    b.Property<int>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SummaryId"));

                    b.Property<double>("AverageSpeedKmh")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageWaitTimeSec")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Intersection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntersectionId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCyclists")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPedestrians")
                        .HasColumnType("integer");

                    b.Property<int>("TotalVehicles")
                        .HasColumnType("integer");

                    b.HasKey("SummaryId");

                    b.ToTable("daily_summaries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
