// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficLightData;

#nullable disable

namespace TrafficLightData.Migrations
{
    [DbContext(typeof(TrafficLightDbContext))]
    [Migration("20251015002412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrafficLightData.Entities.IntersectionEntity", b =>
                {
                    b.Property<int>("IntersectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntersectionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<int>("LightCount")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("MappedLightIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IntersectionId");

                    b.ToTable("intersections");

                    b.HasData(
                        new
                        {
                            IntersectionId = 1,
                            CreatedAt = new DateTime(2025, 10, 8, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 38.004677m,
                            LightCount = 2,
                            Location = "Agiou Spyridonos & Dimitsanas Street",
                            Longitude = 23.676086m,
                            MappedLightIdsJson = "[101, 102]",
                            Name = "Agiou Spyridonos"
                        },
                        new
                        {
                            IntersectionId = 2,
                            CreatedAt = new DateTime(2025, 10, 8, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 38.003558m,
                            LightCount = 2,
                            Location = "Eastern Gate",
                            Longitude = 23.678042m,
                            MappedLightIdsJson = "[201, 202]",
                            Name = "Anatoliki Pyli"
                        },
                        new
                        {
                            IntersectionId = 3,
                            CreatedAt = new DateTime(2025, 10, 8, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 38.002644m,
                            LightCount = 3,
                            Location = "Western Gate",
                            Longitude = 23.674499m,
                            MappedLightIdsJson = "[301, 302, 303]",
                            Name = "Dytiki Pyli"
                        },
                        new
                        {
                            IntersectionId = 4,
                            CreatedAt = new DateTime(2025, 10, 8, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 38.001580m,
                            LightCount = 3,
                            Location = "Church Intersection",
                            Longitude = 23.673638m,
                            MappedLightIdsJson = "[401, 402, 403]",
                            Name = "Ekklisia"
                        },
                        new
                        {
                            IntersectionId = 5,
                            CreatedAt = new DateTime(2025, 10, 8, 7, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 38.004456m,
                            LightCount = 2,
                            Location = "Central Gate",
                            Longitude = 23.676483m,
                            MappedLightIdsJson = "[501, 502]",
                            Name = "Kentriki Pyli"
                        });
                });

            modelBuilder.Entity("TrafficLightData.Entities.TrafficConfigurationEntity", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigurationId"));

                    b.Property<int>("CycleDurationSec")
                        .HasColumnType("int");

                    b.Property<int>("GlobalOffsetSec")
                        .HasColumnType("int");

                    b.Property<int?>("IntersectionEntityIntersectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhaseDurationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfigurationId");

                    b.HasIndex("IntersectionEntityIntersectionId");

                    b.ToTable("traffic_configurations");

                    b.HasData(
                        new
                        {
                            ConfigurationId = 1,
                            CycleDurationSec = 60,
                            GlobalOffsetSec = 10,
                            LastUpdated = new DateTime(2025, 10, 8, 7, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Standard",
                            PhaseDurationsJson = "{\"Green\":40, \"Yellow\":5, \"Red\":15}",
                            Purpose = "Balanced baseline cycle. 40 s green handles moderate mixed traffic."
                        },
                        new
                        {
                            ConfigurationId = 2,
                            CycleDurationSec = 75,
                            GlobalOffsetSec = 20,
                            LastUpdated = new DateTime(2025, 10, 8, 17, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Peak",
                            PhaseDurationsJson = "{\"Green\":50, \"Yellow\":5, \"Red\":20}",
                            Purpose = "Longer green for heavy traffic periods."
                        },
                        new
                        {
                            ConfigurationId = 3,
                            CycleDurationSec = 50,
                            GlobalOffsetSec = 0,
                            LastUpdated = new DateTime(2025, 10, 8, 23, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Night",
                            PhaseDurationsJson = "{\"Green\":15, \"Yellow\":5, \"Red\":30}",
                            Purpose = "Short green, long red for minimal traffic."
                        },
                        new
                        {
                            ConfigurationId = 4,
                            CycleDurationSec = 30,
                            GlobalOffsetSec = 0,
                            LastUpdated = new DateTime(2025, 10, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Emergency",
                            PhaseDurationsJson = "{\"Green\":25, \"Yellow\":3, \"Red\":2}",
                            Purpose = "Immediate priority for emergency vehicles."
                        },
                        new
                        {
                            ConfigurationId = 5,
                            CycleDurationSec = 65,
                            GlobalOffsetSec = 10,
                            LastUpdated = new DateTime(2025, 10, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "PublicTransport",
                            PhaseDurationsJson = "{\"Green\":45, \"Yellow\":5, \"Red\":15}",
                            Purpose = "Extended green for bus approach."
                        },
                        new
                        {
                            ConfigurationId = 6,
                            CycleDurationSec = 40,
                            GlobalOffsetSec = 0,
                            LastUpdated = new DateTime(2025, 10, 9, 17, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Pedestrian",
                            PhaseDurationsJson = "{\"Green\":20, \"Yellow\":5, \"Red\":15}",
                            Purpose = "Half-cycle pedestrian focus."
                        },
                        new
                        {
                            ConfigurationId = 7,
                            CycleDurationSec = 50,
                            GlobalOffsetSec = 5,
                            LastUpdated = new DateTime(2025, 10, 9, 8, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Cyclist",
                            PhaseDurationsJson = "{\"Green\":30, \"Yellow\":5, \"Red\":15}",
                            Purpose = "Cycle optimized for bicycle flow."
                        },
                        new
                        {
                            ConfigurationId = 8,
                            CycleDurationSec = 20,
                            GlobalOffsetSec = 0,
                            LastUpdated = new DateTime(2025, 10, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Incident",
                            PhaseDurationsJson = "{\"Green\":0, \"Yellow\":0, \"Red\":20}",
                            Purpose = "Lock red in case of crash or obstruction."
                        },
                        new
                        {
                            ConfigurationId = 9,
                            CycleDurationSec = 60,
                            GlobalOffsetSec = 0,
                            LastUpdated = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Manual",
                            PhaseDurationsJson = "{\"Green\":20, \"Yellow\":5, \"Red\":35}",
                            Purpose = "Operator control mode."
                        },
                        new
                        {
                            ConfigurationId = 10,
                            CycleDurationSec = 10,
                            GlobalOffsetSec = 0,
                            LastUpdated = new DateTime(2025, 10, 10, 12, 5, 0, 0, DateTimeKind.Utc),
                            Mode = "Failover",
                            PhaseDurationsJson = "{\"Green\":2, \"Yellow\":3, \"Red\":5}",
                            Purpose = "Flashing yellow fallback mode."
                        });
                });

            modelBuilder.Entity("TrafficLightData.Entities.TrafficLightEntity", b =>
                {
                    b.Property<int>("LightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LightId"));

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IntersectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("LightName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.HasKey("LightId");

                    b.HasIndex("IntersectionId");

                    b.ToTable("traffic_lights");

                    b.HasData(
                        new
                        {
                            LightId = 101,
                            Direction = "Agiou Spyridonos",
                            IntersectionId = 1,
                            IsOperational = true,
                            Latitude = 38.004685m,
                            LightName = "agiou-spyridonos101",
                            Longitude = 23.676139m
                        },
                        new
                        {
                            LightId = 102,
                            Direction = "Dimitsanas",
                            IntersectionId = 1,
                            IsOperational = true,
                            Latitude = 38.004640m,
                            LightName = "dimitsanas102",
                            Longitude = 23.676094m
                        },
                        new
                        {
                            LightId = 201,
                            Direction = "Anatoliki Pyli",
                            IntersectionId = 2,
                            IsOperational = true,
                            Latitude = 38.003549m,
                            LightName = "anatoliki-pyli201",
                            Longitude = 23.677997m
                        },
                        new
                        {
                            LightId = 202,
                            Direction = "Agiou Spyridonos",
                            IntersectionId = 2,
                            IsOperational = true,
                            Latitude = 38.003570m,
                            LightName = "agiou-spyridonos202",
                            Longitude = 23.678093m
                        },
                        new
                        {
                            LightId = 301,
                            Direction = "Dytiki Pyli",
                            IntersectionId = 3,
                            IsOperational = true,
                            Latitude = 38.002648m,
                            LightName = "dytiki-pyli301",
                            Longitude = 23.674531m
                        },
                        new
                        {
                            LightId = 302,
                            Direction = "Dimitsanas North",
                            IntersectionId = 3,
                            IsOperational = true,
                            Latitude = 38.002696m,
                            LightName = "dimitsanas-north302",
                            Longitude = 23.674498m
                        },
                        new
                        {
                            LightId = 303,
                            Direction = "Dimitsanas South",
                            IntersectionId = 3,
                            IsOperational = true,
                            Latitude = 38.002606m,
                            LightName = "dimitsanas-south303",
                            Longitude = 23.674487m
                        },
                        new
                        {
                            LightId = 401,
                            Direction = "Dimitsanas",
                            IntersectionId = 4,
                            IsOperational = true,
                            Latitude = 38.001626m,
                            LightName = "dimitsanas401",
                            Longitude = 23.673627m
                        },
                        new
                        {
                            LightId = 402,
                            Direction = "Edessis",
                            IntersectionId = 4,
                            IsOperational = true,
                            Latitude = 38.001583m,
                            LightName = "edessis402",
                            Longitude = 23.673566m
                        },
                        new
                        {
                            LightId = 403,
                            Direction = "Korytsas",
                            IntersectionId = 4,
                            IsOperational = true,
                            Latitude = 38.001596m,
                            LightName = "korytsas403",
                            Longitude = 23.673686m
                        },
                        new
                        {
                            LightId = 501,
                            Direction = "Kentriki Pyli",
                            IntersectionId = 5,
                            IsOperational = true,
                            Latitude = 38.004447m,
                            LightName = "kentriki-pyli501",
                            Longitude = 23.676453m
                        },
                        new
                        {
                            LightId = 502,
                            Direction = "Agiou Spyridonos",
                            IntersectionId = 5,
                            IsOperational = true,
                            Latitude = 38.004467m,
                            LightName = "agiou-spyridonos502",
                            Longitude = 23.676528m
                        });
                });

            modelBuilder.Entity("TrafficLightData.Entities.TrafficConfigurationEntity", b =>
                {
                    b.HasOne("TrafficLightData.Entities.IntersectionEntity", null)
                        .WithMany("Configurations")
                        .HasForeignKey("IntersectionEntityIntersectionId");
                });

            modelBuilder.Entity("TrafficLightData.Entities.TrafficLightEntity", b =>
                {
                    b.HasOne("TrafficLightData.Entities.IntersectionEntity", "Intersection")
                        .WithMany("TrafficLights")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intersection");
                });

            modelBuilder.Entity("TrafficLightData.Entities.IntersectionEntity", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("TrafficLights");
                });
#pragma warning restore 612, 618
        }
    }
}
